USE [master]
GO

/****** Object:  Database [BD_COMPANIA]    Script Date: 11/4/2017 9:29:45 AM ******/
CREATE DATABASE [BD_COMPANIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BD_COMPANIA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BD_COMPANIA.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BD_COMPANIA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\BD_COMPANIA_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BD_COMPANIA] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BD_COMPANIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BD_COMPANIA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET ARITHABORT OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BD_COMPANIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BD_COMPANIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BD_COMPANIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BD_COMPANIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET RECOVERY FULL 
GO

ALTER DATABASE [BD_COMPANIA] SET  MULTI_USER 
GO

ALTER DATABASE [BD_COMPANIA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BD_COMPANIA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BD_COMPANIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BD_COMPANIA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BD_COMPANIA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BD_COMPANIA] SET  READ_WRITE 
GO


USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[ACTIVIDAD]    Script Date: 11/4/2017 9:31:20 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ACTIVIDAD](
	[id_actividad] [int] NOT NULL IDENTITY(1,1),
	[codigo] [nchar](20) NULL,
	[nombre] [nchar](20) NULL,
	[descripcion] [nchar](60) NULL,
	[id_pantalla] [int] NULL,
	[tipo_firma] [char](1) NULL,
	[rol_seguridad] [char](1) NULL,
	[requerido] [char](1) NULL,
	[tiempo_minutos] [int] NULL,
	[tipo_empleado] [char](1) NULL,
	[periodica] [char](1) NULL,
 CONSTRAINT [PK_ACTIVIDAD] PRIMARY KEY CLUSTERED 
(
	[id_actividad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[AD_HOC]    Script Date: 11/4/2017 9:31:38 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[AD_HOC](
	[id_adhoc] [int] NOT NULL IDENTITY(1,1),
	[nombre] [nchar](20) NULL,
	[codigo] [nchar](20) NULL,
	[descripcion] [nchar](60) NULL,
	[tipo_firma] [char](1) NULL,
	[rol_seguridad] [char](1) NULL,
 CONSTRAINT [PK_AD_HOC] PRIMARY KEY CLUSTERED 
(
	[id_adhoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[BITACORA]    Script Date: 11/4/2017 9:32:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BITACORA](
	[id_bitacora] [int] NOT NULL IDENTITY(1,1),
	[id_actividad] [int] NULL,
	[valores_ingresados] [int] NULL,
	[fecha] [datetime] NULL,
	[usuario] [nchar](20) NULL

 CONSTRAINT [PK_BITACORA] PRIMARY KEY CLUSTERED 
(
	[id_bitacora] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[CIERRE_PRODUCCION]    Script Date: 11/4/2017 9:32:52 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CIERRE_PRODUCCION](
	[id_orden] [int] NOT NULL,
	[line_num] [int] NOT NULL IDENTITY (1,1),
	[turno] [int] NULL,
	[cantidad] [int] NULL

CONSTRAINT [PK_CIERRE_PRODUCCION] PRIMARY KEY CLUSTERED 
(
	[id_orden] ASC,
	[line_num] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

) ON [PRIMARY]

GO

USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[COPIA_ACTIVIDAD]    Script Date: 11/4/2017 9:33:12 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[COPIA_ACTIVIDAD](
	[id_actividad] [int] NOT NULL IDENTITY(1,1),
	[codigo] [nchar](20) NULL,
	[nombre] [nchar](20) NULL,
	[descripcion] [nchar](60) NULL,
	[id_pantalla] [int] NULL,
	[tipo_firma] [char](1) NULL,
	[rol_seguridad] [char](1) NULL,
	[requerido] [char](1) NULL,
	[tiempo_minutos] [int] NULL,
	[tipo_empleado] [char](1) NULL,
 CONSTRAINT [PK_COPIA_ACTIVIDAD] PRIMARY KEY CLUSTERED 
(
	[id_actividad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[COPIA_FLUJO]    Script Date: 11/4/2017 9:33:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COPIA_FLUJO](
	[id_flujo] [int] NOT NULL IDENTITY(1,1),
 CONSTRAINT [PK_COPIA_FLUJO] PRIMARY KEY CLUSTERED 
(
	[id_flujo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[COPIA_FLUJO_PROCESO]    Script Date: 11/4/2017 9:33:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COPIA_FLUJO_PROCESO](
	[id_flujo_proceso] [int] NOT NULL IDENTITY(1,1),
	[id_actividad] [int] NULL,
	[id_flujo] [int] NULL,
 CONSTRAINT [PK_COPIA_FLUJO_PROCESO] PRIMARY KEY CLUSTERED 
(
	[id_flujo_proceso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[COPIA_PREDECESORA]    Script Date: 11/4/2017 9:34:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COPIA_PREDECESORA](
	[id_predecesora] [int] NOT NULL IDENTITY(1,1),
	[id_actual] [int] NULL,
	[id_anterior] [int] NULL,
 CONSTRAINT [PK_COPIA_PREDECESORA] PRIMARY KEY CLUSTERED 
(
	[id_predecesora] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[DOCUMENTO]    Script Date: 11/4/2017 9:35:32 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DOCUMENTO](
	[id_documento] [int] NOT NULL IDENTITY(1,1),
	[id_producto] [int] NULL,
	[nombre] [nchar](30) NULL,
	[fecha] [date] NULL,
 CONSTRAINT [PK_DOCUMENTO] PRIMARY KEY CLUSTERED 
(
	[id_documento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[EMPLEADO]    Script Date: 11/4/2017 9:36:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLEADO](
	[id_empleado] [int] NOT NULL IDENTITY(1,1),
	[nombre] [nchar](50) NULL,
	[id_rol] [int] NULL,
	[id_tipo] [int] NULL,
	[usuario] [nchar](20) NULL,
	[contraseña] [nchar](20) NULL,
 CONSTRAINT [PK_EMPLEADO] PRIMARY KEY CLUSTERED 
(
	[id_empleado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[FIRMA]    Script Date: 11/4/2017 9:36:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FIRMA](
	[id_firma] [int] NOT NULL IDENTITY(1,1),
	[id_rol] [int] NULL,
	[id_actividad] [int] NULL,
	[id_empleado] [int] NULL,
	[fecha] [datetime] NULL,
 CONSTRAINT [PK_FIRMA] PRIMARY KEY CLUSTERED 
(
	[id_firma] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[FLUJO]    Script Date: 11/4/2017 9:36:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FLUJO](
	[id_flujo] [int] NOT NULL IDENTITY(1,1),
 CONSTRAINT [PK_FLUJO] PRIMARY KEY CLUSTERED 
(
	[id_flujo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[FLUJO_PROCESO]    Script Date: 11/4/2017 9:36:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FLUJO_PROCESO](
	[id_flujo_proceso] [int] NOT NULL IDENTITY(1,1),
	[id_actividad] [int] NULL,
	[id_flujo] [int] NULL,
 CONSTRAINT [PK_FLUJO_PROCESO] PRIMARY KEY CLUSTERED 
(
	[id_flujo_proceso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[LINEA]    Script Date: 11/4/2017 9:37:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LINEA](
	[id_linea] [int] NOT NULL IDENTITY(1,1),
	[descripcion] [nchar](60) NULL,
 CONSTRAINT [PK_LINEA] PRIMARY KEY CLUSTERED 
(
	[id_linea] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[LISTA_CHEQUEO]    Script Date: 11/4/2017 9:37:36 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LISTA_CHEQUEO](
	[id_actividad] [int] NOT NULL,
	[line_num] [int] NOT NULL IDENTITY(1,1),
	[texto] [nchar](60) NULL,
	[resultado] [char](1) NULL,
	[fecha] [date] NULL,
	[usuario] [nchar](20) NULL,
 CONSTRAINT [PK_LISTA_CHEQUEO] PRIMARY KEY CLUSTERED 
(
	[id_actividad] ASC,
	[line_num] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[LISTA_MATERIAL]    Script Date: 11/4/2017 9:37:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LISTA_MATERIAL](
	[id_producto] [int] NOT NULL,
	[linea_num] [int] NOT NULL IDENTITY(1,1),
	[id_material] [int] NULL,
 CONSTRAINT [PK_LISTA_MATERIAL] PRIMARY KEY CLUSTERED 
(
	[id_producto] ASC,
	[linea_num] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[MATERIAL]    Script Date: 11/4/2017 9:38:07 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MATERIAL](
	[id_material] [int] NOT NULL IDENTITY(1,1),
	[nombre] [nchar](20) NULL,
 CONSTRAINT [PK_MATERIAL] PRIMARY KEY CLUSTERED 
(
	[id_material] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[ORDEN]    Script Date: 11/4/2017 9:38:18 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ORDEN](
	[id_orden] [int] NOT NULL IDENTITY(1,1),
	[lote] [nchar](10) NULL,
	[id_producto] [int] NULL,
	[id_linea] [int] NULL,
	[fecha_creacion] [datetime] NULL,
	[fecha_finalizacion] [datetime] NULL,
	[status] [char](1) NULL,
	[id_copia_flujo] [int] NULL,
 CONSTRAINT [PK_ORDEN] PRIMARY KEY CLUSTERED 
(
	[id_orden] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[PANTALLA]    Script Date: 11/4/2017 9:38:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PANTALLA](
	[id_pantalla] [int] NOT NULL IDENTITY(1,1),
	[codigo] [nchar](20) NULL,
	[nombre] [nchar](15) NULL,
	[tipo] [int] NULL,
 CONSTRAINT [PK_PANTALLA] PRIMARY KEY CLUSTERED 
(
	[id_pantalla] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[PREDECESORA]    Script Date: 11/4/2017 9:39:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PREDECESORA](
	[id_predecesora] [int] NOT NULL IDENTITY(1,1),
	[id_actual] [int] NULL,
	[id_anterior] [int] NULL,
 CONSTRAINT [PK_PREDECESORA] PRIMARY KEY CLUSTERED 
(
	[id_predecesora] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 11/4/2017 9:39:13 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRODUCTO](
	[id_producto] [int] NOT NULL IDENTITY(1,1),
	[id_flujo] [int] NULL,
	[descripcion] [nchar](50) NULL,
 CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[id_producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[ROL]    Script Date: 11/4/2017 9:39:25 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ROL](
	[id_rol] [int] NOT NULL IDENTITY(1,1),
	[nombre] [nchar](20) NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[id_rol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[TIPO]    Script Date: 11/4/2017 9:39:38 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIPO](
	[id_tipo] [int] NOT NULL IDENTITY(1,1),
	[nombre] [nchar](20) NULL,
 CONSTRAINT [PK_TIPO] PRIMARY KEY CLUSTERED 
(
	[id_tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [BD_COMPANIA]
GO

/****** Object:  Table [dbo].[TIPO_PANTALLA]    Script Date: 11/4/2017 9:39:50 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TIPO_PANTALLA](
	[id_tipo] [int] NOT NULL IDENTITY(1,1),
	[nombre] [nchar](20) NULL,
 CONSTRAINT [PK_TIPO_PANTALLA] PRIMARY KEY CLUSTERED 
(
	[id_tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[PRODUCTO]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCTO_FLUJO] FOREIGN KEY([id_flujo])
REFERENCES [dbo].[FLUJO] ([id_flujo])
GO

ALTER TABLE [dbo].[PRODUCTO] CHECK CONSTRAINT [FK_PRODUCTO_FLUJO]
GO

ALTER TABLE [dbo].[PREDECESORA]  WITH CHECK ADD  CONSTRAINT [FK_PREDECESORA_FLUJO_PROCESO] FOREIGN KEY([id_actual])
REFERENCES [dbo].[FLUJO_PROCESO] ([id_flujo_proceso])
GO

ALTER TABLE [dbo].[PREDECESORA] CHECK CONSTRAINT [FK_PREDECESORA_FLUJO_PROCESO]
GO

ALTER TABLE [dbo].[PREDECESORA]  WITH CHECK ADD  CONSTRAINT [FK_PREDECESORA_FLUJO_PROCESO1] FOREIGN KEY([id_anterior])
REFERENCES [dbo].[FLUJO_PROCESO] ([id_flujo_proceso])
GO

ALTER TABLE [dbo].[PREDECESORA] CHECK CONSTRAINT [FK_PREDECESORA_FLUJO_PROCESO1]
GO

ALTER TABLE [dbo].[PANTALLA]  WITH CHECK ADD  CONSTRAINT [FK_PANTALLA_TIPO_PANTALLA] FOREIGN KEY([tipo])
REFERENCES [dbo].[TIPO_PANTALLA] ([id_tipo])
GO

ALTER TABLE [dbo].[PANTALLA] CHECK CONSTRAINT [FK_PANTALLA_TIPO_PANTALLA]
GO

ALTER TABLE [dbo].[ORDEN]  WITH CHECK ADD  CONSTRAINT [FK_ORDEN_COPIA_FLUJO] FOREIGN KEY([id_copia_flujo])
REFERENCES [dbo].[COPIA_FLUJO] ([id_flujo])
GO

ALTER TABLE [dbo].[ORDEN] CHECK CONSTRAINT [FK_ORDEN_COPIA_FLUJO]
GO

ALTER TABLE [dbo].[ORDEN]  WITH CHECK ADD  CONSTRAINT [FK_ORDEN_LINEA] FOREIGN KEY([id_linea])
REFERENCES [dbo].[LINEA] ([id_linea])
GO

ALTER TABLE [dbo].[ORDEN] CHECK CONSTRAINT [FK_ORDEN_LINEA]
GO

ALTER TABLE [dbo].[ORDEN]  WITH CHECK ADD  CONSTRAINT [FK_ORDEN_PRODUCTO] FOREIGN KEY([id_producto])
REFERENCES [dbo].[PRODUCTO] ([id_producto])
GO

ALTER TABLE [dbo].[ORDEN] CHECK CONSTRAINT [FK_ORDEN_PRODUCTO]
GO

ALTER TABLE [dbo].[LISTA_MATERIAL]  WITH CHECK ADD  CONSTRAINT [FK_LISTA_MATERIAL_MATERIAL] FOREIGN KEY([id_material])
REFERENCES [dbo].[MATERIAL] ([id_material])
GO

ALTER TABLE [dbo].[LISTA_MATERIAL] CHECK CONSTRAINT [FK_LISTA_MATERIAL_MATERIAL]
GO

ALTER TABLE [dbo].[LISTA_MATERIAL]  WITH CHECK ADD  CONSTRAINT [FK_LISTA_MATERIAL_PRODUCTO] FOREIGN KEY([id_producto])
REFERENCES [dbo].[PRODUCTO] ([id_producto])
GO

ALTER TABLE [dbo].[LISTA_MATERIAL] CHECK CONSTRAINT [FK_LISTA_MATERIAL_PRODUCTO]
GO

ALTER TABLE [dbo].[LISTA_CHEQUEO]  WITH CHECK ADD  CONSTRAINT [FK_LISTA_CHEQUEO_ACTIVIDAD] FOREIGN KEY([id_actividad])
REFERENCES [dbo].[ACTIVIDAD] ([id_actividad])
GO

ALTER TABLE [dbo].[LISTA_CHEQUEO] CHECK CONSTRAINT [FK_LISTA_CHEQUEO_ACTIVIDAD]
GO

ALTER TABLE [dbo].[FLUJO_PROCESO]  WITH CHECK ADD  CONSTRAINT [FK_FLUJO_PROCESO_ACTIVIDAD] FOREIGN KEY([id_actividad])
REFERENCES [dbo].[ACTIVIDAD] ([id_actividad])
GO

ALTER TABLE [dbo].[FLUJO_PROCESO] CHECK CONSTRAINT [FK_FLUJO_PROCESO_ACTIVIDAD]
GO

ALTER TABLE [dbo].[FLUJO_PROCESO]  WITH CHECK ADD  CONSTRAINT [FK_FLUJO_PROCESO_FLUJO] FOREIGN KEY([id_flujo])
REFERENCES [dbo].[FLUJO] ([id_flujo])
GO

ALTER TABLE [dbo].[FLUJO_PROCESO] CHECK CONSTRAINT [FK_FLUJO_PROCESO_FLUJO]
GO

ALTER TABLE [dbo].[FIRMA]  WITH CHECK ADD  CONSTRAINT [FK_FIRMA_ACTIVIDAD] FOREIGN KEY([id_actividad])
REFERENCES [dbo].[ACTIVIDAD] ([id_actividad])
GO

ALTER TABLE [dbo].[FIRMA] CHECK CONSTRAINT [FK_FIRMA_ACTIVIDAD]
GO

ALTER TABLE [dbo].[FIRMA]  WITH CHECK ADD  CONSTRAINT [FK_FIRMA_EMPLEADO] FOREIGN KEY([id_empleado])
REFERENCES [dbo].[EMPLEADO] ([id_empleado])
GO

ALTER TABLE [dbo].[FIRMA] CHECK CONSTRAINT [FK_FIRMA_EMPLEADO]
GO

ALTER TABLE [dbo].[FIRMA]  WITH CHECK ADD  CONSTRAINT [FK_FIRMA_ROL] FOREIGN KEY([id_rol])
REFERENCES [dbo].[ROL] ([id_rol])
GO

ALTER TABLE [dbo].[FIRMA] CHECK CONSTRAINT [FK_FIRMA_ROL]
GO

ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_ROL] FOREIGN KEY([id_rol])
REFERENCES [dbo].[ROL] ([id_rol])
GO

ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_ROL]
GO

ALTER TABLE [dbo].[EMPLEADO]  WITH CHECK ADD  CONSTRAINT [FK_EMPLEADO_TIPO] FOREIGN KEY([id_tipo])
REFERENCES [dbo].[TIPO] ([id_tipo])
GO

ALTER TABLE [dbo].[EMPLEADO] CHECK CONSTRAINT [FK_EMPLEADO_TIPO]
GO

ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [FK_DOCUMENTO_PRODUCTO] FOREIGN KEY([id_producto])
REFERENCES [dbo].[PRODUCTO] ([id_producto])
GO

ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [FK_DOCUMENTO_PRODUCTO]
GO

ALTER TABLE [dbo].[COPIA_PREDECESORA]  WITH CHECK ADD  CONSTRAINT [FK_COPIA_PREDECESORA_COPIA_FLUJO_PROCESO] FOREIGN KEY([id_actual])
REFERENCES [dbo].[COPIA_FLUJO_PROCESO] ([id_flujo_proceso])
GO

ALTER TABLE [dbo].[COPIA_PREDECESORA] CHECK CONSTRAINT [FK_COPIA_PREDECESORA_COPIA_FLUJO_PROCESO]
GO

ALTER TABLE [dbo].[COPIA_PREDECESORA]  WITH CHECK ADD  CONSTRAINT [FK_COPIA_PREDECESORA_COPIA_FLUJO_PROCESO1] FOREIGN KEY([id_anterior])
REFERENCES [dbo].[COPIA_FLUJO_PROCESO] ([id_flujo_proceso])
GO

ALTER TABLE [dbo].[COPIA_PREDECESORA] CHECK CONSTRAINT [FK_COPIA_PREDECESORA_COPIA_FLUJO_PROCESO1]
GO

ALTER TABLE [dbo].[COPIA_FLUJO_PROCESO]  WITH CHECK ADD  CONSTRAINT [FK_COPIA_FLUJO_PROCESO_COPIA_ACTIVIDAD] FOREIGN KEY([id_actividad])
REFERENCES [dbo].[COPIA_ACTIVIDAD] ([id_actividad])
GO

ALTER TABLE [dbo].[COPIA_FLUJO_PROCESO] CHECK CONSTRAINT [FK_COPIA_FLUJO_PROCESO_COPIA_ACTIVIDAD]
GO

ALTER TABLE [dbo].[COPIA_FLUJO_PROCESO]  WITH CHECK ADD  CONSTRAINT [FK_COPIA_FLUJO_PROCESO_COPIA_FLUJO] FOREIGN KEY([id_flujo])
REFERENCES [dbo].[COPIA_FLUJO] ([id_flujo])
GO

ALTER TABLE [dbo].[COPIA_FLUJO_PROCESO] CHECK CONSTRAINT [FK_COPIA_FLUJO_PROCESO_COPIA_FLUJO]
GO

ALTER TABLE [dbo].[CIERRE_PRODUCCION]  WITH CHECK ADD  CONSTRAINT [FK_CIERRE_PRODUCCION_ORDEN] FOREIGN KEY([id_orden])
REFERENCES [dbo].[ORDEN] ([id_orden])
GO

ALTER TABLE [dbo].[CIERRE_PRODUCCION] CHECK CONSTRAINT [FK_CIERRE_PRODUCCION_ORDEN]
GO

ALTER TABLE [dbo].[BITACORA]  WITH CHECK ADD  CONSTRAINT [FK_BITACORA_ACTIVIDAD] FOREIGN KEY([id_actividad])
REFERENCES [dbo].[ACTIVIDAD] ([id_actividad])
GO

ALTER TABLE [dbo].[BITACORA] CHECK CONSTRAINT [FK_BITACORA_ACTIVIDAD]
GO

ALTER TABLE [dbo].[ACTIVIDAD]  WITH CHECK ADD  CONSTRAINT [FK_ACTIVIDAD_PANTALLA] FOREIGN KEY([id_pantalla])
REFERENCES [dbo].[PANTALLA] ([id_pantalla])
GO

ALTER TABLE [dbo].[ACTIVIDAD] CHECK CONSTRAINT [FK_ACTIVIDAD_PANTALLA]
GO