
CREATE PROCEDURE CrearMaterial @nombre nchar(20)
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY 
		BEGIN TRAN
			INSERT INTO MATERIAL (nombre) VALUES (@nombre)
		COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
	END CATCH
END
GO
